import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "./components/sidebar";
import SiteHeader from "./components/siteHeader";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Sidebar />
        <main className="ml-[250px]">
          <SiteHeader />
          <div className="bg-[#f5f7fa] site-main-section">
            {children}
          </div>

        </main>
        </body>
    </html>
  );
}
